drivers: misc: motomods: Remove unused variables
Clang warns:
../kernel/motorola/msm8953/drivers/misc/motomods/greybus/camera_ext_ctrls.c:589:18: error: unused variable 'control_ae_precapture_trigger_items' [-Werror,-Wunused-const-variable]
static const s64 control_ae_precapture_trigger_items[] = {
../kernel/motorola/msm8953/drivers/misc/motomods/greybus/camera_ext_ctrls.c:1255:18: error: unused variable 'capture_items' [-Werror,-Wunused-const-variable]
static const u64 capture_items[] = {

Change-Id: Ieb0d2d64231bcc9376818e471747ca1632c815fe